#!/usr/bin/env python3
import os
import re
from matplotlib.lines import Line2D
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from matplotlib.patches import Patch
import pingouin as pg

# ==========================================
# 1. CONFIGURATION
# ==========================================
SURVEY_CSV = "/media/abolghasem/51AC-250D/test_set/results-survey895791.csv"  # Update with your actual path
#VLM_PREDICTIONS_CSV = "/media/abolghasem/51AC-250D/test_set/Final_test_set/VLM_SU_D_predictions_run_0.csv" # Update with your VLM output (can be merged runs)
VLM_CSVS = {
    "Prompt A": "/media/abolghasem/51AC-250D/test_set/Final_test_set/VLM_SU_A_predictions_run_0.csv",
    "Prompt B": "/media/abolghasem/51AC-250D/test_set/Final_test_set/VLM_SU_B_predictions_run_0.csv",
    "Prompt C": "/media/abolghasem/51AC-250D/test_set/Final_test_set/VLM_SU_C_predictions_run_0.csv",
    "Prompt D": "/media/abolghasem/51AC-250D/test_set/Final_test_set/VLM_SU_D_predictions_run_0.csv"
}
OUTPUT_PLOT_FILE = "/media/abolghasem/51AC-250D/test_set/test_setoutput_per_scene/crossability_analysis_all_scenes.pdf"  # Directory to save the generated plots
OUTPUT_VIOLIN_FILE = "/media/abolghasem/51AC-250D/test_set/test_setoutput_per_scene/rating_distribution_violin_plot.pdf"  # Directory to save the violin plot
OUTPUT_INDIVIDUAL_PLOT_DIR = "/media/abolghasem/51AC-250D/test_set/test_setoutput_per_scene/individual_plots"  # Directory to save individual scene plots
GT_CSV = "/media/abolghasem/51AC-250D/test_set/Final_test_set/ground_truth_template_by_researcher.csv"  # Path to the GT CSV generated by generate_gt.py
OUT_GT_FILE = "/media/abolghasem/51AC-250D/test_set/test_setoutput_per_scene/survey_vs_gt_comparison.pdf"  # Directory to save the GT comparison plot
OUTPUT_STATS_FILE = "/media/abolghasem/51AC-250D/test_set/test_setoutput_per_scene/statistical_analysis.pdf"
# Create output directory if it doesn't exist
os.makedirs(OUTPUT_INDIVIDUAL_PLOT_DIR, exist_ok=True)
os.makedirs(os.path.dirname(OUT_GT_FILE), exist_ok=True)
os.makedirs(os.path.dirname(OUTPUT_STATS_FILE), exist_ok=True)
# ==========================================
# 2. DATA PROCESSING FUNCTIONS
# ==========================================
def parse_survey_columns(question_str):
    """Extracts the Base Scene, Pair, and Framing from the raw survey header."""
    match = re.search(r'^([A-Za-z0-9]+)\[.*?\[\[(.*?)\].*?(walking|robot)', question_str)
    if not match:
        return None, None, None
    
    scene_raw = match.group(1)
    pair = f"[{match.group(2).replace(' ', '')}]"
    framing_type = match.group(3)
    
    framing = 'Human' if framing_type == 'walking' else 'Robot'
    return scene_raw, pair, framing

def load_and_format_survey_data(csv_path):
    """Processes survey data, preserving individual responses for distribution plots."""
    df = pd.read_csv(csv_path)
    last_page_col = 'lastpage. Last page'
    max_page = df[last_page_col].max() #
    df = df[df[last_page_col] == max_page].copy()  # Keep only completed responses (those that reached the last page)
    print(f"Using {len(df)} completed survey responses (last page = {max_page})")
    
    # Drop irrelevant metadata
    meta_cols = ['id. Response ID', 'submitdate. Date submitted', 'lastpage. Last page', 
                 'startlanguage. Start language', 'seed. Seed', 'startdate. Date started', 
                 'datestamp. Date last action', 'Q00. {rand(1,2)}']
    df_responses = df.drop(columns=[c for c in meta_cols if c in df.columns])
    
    # Melt to long format
    df_long = df_responses.melt(var_name='Question', value_name='Response').dropna(subset=['Response'])
    
    # Map Likert scale
    rating_map = {
        'Strongly Disagree': 0.0,
        'Disagree': 0.25,
        'Neutral': 0.5,
        'Agree': 0.75,
        'Strongly Agree': 1.0
    }
    df_long['Score'] = df_long['Response'].map(rating_map)
    
    # Parse attributes
    df_long[['Scene_Raw', 'Pair', 'Evaluator']] = df_long['Question'].apply(lambda x: pd.Series(parse_survey_columns(x)))
    df_long = df_long.dropna(subset=['Scene_Raw'])
    
    # Normalize Scene nomenclature (Strip 'R' prefix for Robot framing)
    df_long['Base_Scene'] = df_long.apply(
        lambda row: row['Scene_Raw'][1:] if row['Evaluator'] == 'Robot' and row['Scene_Raw'].startswith('R') else row['Scene_Raw'], 
        axis=1
    )

    human_cols = [c for c in df.columns if re.search(r'walking',c) ]
    robot_cols = [c for c in df.columns if re.search(r'robot',c) ]
    n_human_participants = int(df[human_cols].notna().any(axis=1).sum())
    n_robot_participants = int(df[robot_cols].notna().any(axis=1).sum())

    # Keep only what we need for the plot
    return df_long[['Base_Scene', 'Pair', 'Evaluator', 'Score']], n_human_participants, n_robot_participants

def load_and_format_vlm_data(csv_path, vlm_label):
    """Formats VLM prediction data to match the survey structure."""
    df_vlm = pd.read_csv(csv_path)

    
    # Remove errors and standardize Image Type
    df_clean = df_vlm[df_vlm['Image_Type'] != 'ERROR'].copy()
    df_clean['Image_Type'] = df_clean['Image_Type'].astype(str).str.strip().str.title()
    
    # Ensure Score is numeric
    df_clean['Score'] = pd.to_numeric(df_clean['Predicted_Crossability'], errors='coerce')
    df_clean = df_clean.dropna(subset=['Score'])
    
    # Clean Strings
    df_clean['Pair'] = df_clean['Pair'].astype(str).str.replace(' ', '').str.replace("'", "").str.replace('"', "")
    
    # Extract Base Scene (Strip suffixes)
    df_clean['Base_Scene'] = df_clean['Filename'].astype(str).apply(
        lambda x: x.replace('_raw.jpg', '').replace('_annotated.jpg', '').replace('_depth.png', '')
    )
    
    # Rename Image_Type to 'Evaluator' to align with survey data (e.g., "VLM Raw")
    df_clean['Evaluator'] = vlm_label + ' ' + df_clean['Image_Type']
    
    return df_clean[['Base_Scene', 'Pair', 'Evaluator', 'Score']]


def generate_violin_plot(df_master, output_path, n_human_p, n_robot_p):
    survey_only = df_master[df_master['Evaluator'].isin(['Human', 'Robot'])].copy()
    

    palette = {'Human': '#4169E1', 'Robot': '#FF8C00'}
    cat_order = sorted(survey_only['Base_Scene'].apply(lambda x: re.sub(r'\d+', '',x)).unique())
    survey_only['Category'] = survey_only['Base_Scene'].apply(lambda x: re.sub(r'\d+', '',x))

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.patch.set_facecolor('#F0F0F0')

    # Panel A: Overall Violin Plot
    ax = axes[0]
    sns.violinplot(data=survey_only, x='Evaluator', y='Score',
               hue='Evaluator', palette=palette, inner='box',
               cut=0, linewidth=1.5, ax=ax,
               order=['Human', 'Robot'], legend=False)

    sns.stripplot(data=survey_only, x='Evaluator', y='Score',
                hue='Evaluator', palette=palette,
                order=['Human', 'Robot'], legend=False,
                jitter=0.12, size=2.8, alpha=0.35,
                edgecolor='black', linewidth=0.2, ax=ax)

    ax.set_facecolor('#F8F8F8')
    ax.yaxis.grid(True, linestyle='--', alpha=0.5, linewidth=0.6)
    ax.set_axisbelow(True)
    ax.set_ylim(-0.08, 1.12)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    ax.set_yticklabels(['0.0\n(Blocked)', '0.25', '0.50', '0.75', '1.0\n(Open)'])
    ax.set_xlabel('')
    ax.set_ylabel('Crossability Score', fontsize=12)
    ax.set_title('A — Overall\nHuman vs Robot Framing', fontsize=12, fontweight='bold')

    for i, (src, color) in enumerate([('Human', '#4169E1'), ('Robot', '#FF8C00')]):
        m = survey_only[survey_only['Evaluator'] == src]['Score'].mean()
        ax.hlines(m, i - 0.35, i + 0.35, colors=color, linewidth=2.5,
                  linestyles='--', zorder=5)
        ax.text(i + 0.38, m, f'μ={m:.2f}', va='center', fontsize=10,
                color=color, fontweight='bold')


    ax.text(0, -0.07, f'n = {n_human_p} participants', ha='center', fontsize=9,
            color='#4169E1', style='italic')
    ax.text(1, -0.07, f'n = {n_robot_p} participants', ha='center', fontsize=9,
            color='#FF8C00', style='italic')
    
    # Panel B: Per category Violin Plots
    ax2 = axes[1]
    x = np.arange(len(cat_order))
    width = 0.35
    for i, cat in enumerate(cat_order):
        for j, (src, color) in enumerate([('Human', '#4169E1'), ('Robot', '#FF8C00')]):
            vals = survey_only[
                (survey_only['Category'] == cat) &
                (survey_only['Evaluator'] == src)]['Score']
            if len(vals) == 0: continue
            xpos = i + (j - 0.5) * width
            parts = ax2.violinplot(vals, positions=[xpos], widths=width * 0.85,
                                   showmedians=True, showextrema=False)
            for pc in parts['bodies']:
                pc.set_facecolor(color)
                pc.set_alpha(0.55)
            parts['cmedians'].set_color(color)

    sns.swarmplot(data=survey_only, x='Category', y='Score', hue='Evaluator', hue_order=['Human', 'Robot'], palette={'Human': '#4169E1', 'Robot': '#FF8C00'}, dodge=True, size=3.0, alpha=0.8, edgecolor='black', linewidth=0.3, ax=ax2, legend=False, warn_thresh=1.0)

    ax2.legend(handles=[
        Patch(facecolor='#4169E1', alpha=0.7, label=f'Human (n={n_human_p})'),
        Patch(facecolor='#FF8C00', alpha=0.7, label=f'Robot (n={n_robot_p})')],
        fontsize=10, loc='upper right')
    ax2.set_facecolor('#F8F8F8')
    ax2.yaxis.grid(True, linestyle='--', alpha=0.5, linewidth=0.6)
    ax2.set_axisbelow(True)
    ax2.set_ylim(-0.05, 1.15)
    ax2.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    ax2.set_xticks(x)
    ax2.set_xticklabels(cat_order, rotation=20, ha='right', fontsize=10)
    ax2.set_ylabel('Crossability Score', fontsize=12)
    ax2.set_title('B — Per Interaction Category\nHuman vs Robot Framing', fontsize=12, fontweight='bold')

    fig.suptitle('Human vs Robot Framing, Crossability Rating Distribution',
                 fontsize=13, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()

    print(f"---> Violin plot saved to: {output_path}")


# =============
# Plotting the comperesion of the Survey and the reseacher label
def generate_gt_comparison_plot(df_master, gt_csv_path, output_path):
    # Load complete survey dta
    df_raw = pd.read_csv(SURVEY_CSV)
    df_raw.columns = df_raw.columns.str.strip()
    max_page = df_raw['lastpage. Last page'].max()
    df_raw = df_raw[df_raw['lastpage. Last page'] == max_page].copy()
   
    likert = {'Strongly Disagree':0.0,'Disagree':0.25,'Neutral':0.5,
              'Agree':0.75,'Strongly Agree':1.0}
    records = []
    for col in df_raw.columns:
        m = re.match(r'^(R?)([A-Za-z0-9]+)\[SQ\d+\]\.\s+\[\[(\d+)[,\s]+(\d+)\]', col)
        if not m: continue
        scene = m.group(2)
        pair  = f"[{m.group(3)}, {m.group(4)}]"
        src   = 'Robot' if m.group(1)=='R' else 'Human'
        for val in df_raw[col].dropna():
            if val in likert:
                records.append({'Scene':scene,'Pair':pair,'Source':src,'Score':likert[val]})
    survey = pd.DataFrame(records)

    # Load GT data
    gt = pd.read_csv(gt_csv_path)
    gt['Scene'] = gt['Filename'].str.replace(r'_(raw|annotated|depth)\.(jpg|png)$','',regex=True)
    gt_clean = gt[gt['Image_Type']=='Raw'][['Scene','Pair','Actual_Status']].drop_duplicates()
    gt_clean['Pair'] = gt_clean['Pair'].str.strip()
    survey['Pair'] = survey['Pair'].str.strip()
    merged = survey.merge(gt_clean, on=['Scene','Pair'], how='inner')

    # Stats per group
    order = ['Blocked', 'Open']
    print("\nMean + SD for four conditions (Blocked/Open × Human/Robot):")
    print("="*60)
    for status in order:
        for src in ['Human', 'Robot']:
            grp = merged[(merged['Actual_Status'] == status) & (merged['Source'] == src)]['Score']
            print(f"{status} / {src}: "
              f"mean={grp.mean():.3f}, "
              f"SD={grp.std():.3f}, "
              f"N={len(grp)}")
            
    
            
    palette = {'Human': '#4169E1', 'Robot': '#FF8C00'}
    # Removed grid parameters (1, 2) to yield a single Axes object
    fig, ax_gt = plt.subplots(figsize=(10, 7))
    fig.patch.set_facecolor('#F0F0F0')

    # Violin
    sns.violinplot(data=merged, x='Actual_Status', y='Score',
                   hue='Source', hue_order=['Human', 'Robot'],
                   palette=palette, inner=None, cut=0,
                   linewidth=1.2, ax=ax_gt, order=order,
                   dodge=True, alpha=0.45)

    # Swarm on top
    sns.swarmplot(data=merged, x='Actual_Status', y='Score',
                  hue='Source', hue_order=['Human', 'Robot'],
                  palette=palette, order=order,
                  dodge=True, size=2.8, alpha=0.75,
                  edgecolor='black', linewidth=0.25,
                  ax=ax_gt, legend=False, warn_thresh=1.0)
    
    # ── Mean lines per group (Human and Robot) per GT status ─────────────────
    offsets = {'Human': -0.22, 'Robot': 0.22}
    
    for i, status in enumerate(order):
        for src, color in [('Human', '#4169E1'), ('Robot', '#FF8C00')]:
            grp = merged[(merged['Actual_Status'] == status) & 
                         (merged['Source'] == src)]['Score']
            m_val = grp.mean()
            xc = i + offsets[src]
            ax_gt.hlines(m_val, xc - 0.18, xc + 0.18,
                         colors=color, linewidth=3.5,
                         linestyles='solid', zorder=6)
            ax_gt.text(xc + 0.20, m_val, f'μ={m_val:.2f}',
                       va='center', fontsize=9.5, color=color, fontweight='bold')
            
    expected = {'Blocked': 0.0, 'Open': 1.0}
    for i, status in enumerate(order):
        ax_gt.hlines(expected[status], i - 0.48, i + 0.48,
                  colors='#222222', linewidth=3.5,        # ← thick dark dashed
                  linestyles=(0, (6, 3)), zorder=10)
        label = 'Expected: (fully blocked)' if status == 'Blocked' else 'Expected: (fully open)'
        y_offset = 0.05 if status == 'Blocked' else -0.07
        ax_gt.text(i, expected[status] + y_offset, label,
                ha='center', fontsize=9, color='#222222',
                style='italic', fontweight='bold')
        

    
    # Formating
    ax_gt.set_facecolor('#F8F8F8')
    ax_gt.yaxis.grid(True, linestyle='--', alpha=0.4, linewidth=0.6)
    ax_gt.set_axisbelow(True)
    ax_gt.set_ylim(-0.12, 1.22)
    ax_gt.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    ax_gt.set_yticklabels(['0.0  (Blocked)', '0.25', '0.50', '0.75', '1.0  (Open)'], fontsize=11)
    ax_gt.set_xlabel('Researcher Label', fontsize=13)
    ax_gt.set_ylabel('Participant Crossability Score', fontsize=13)
    ax_gt.set_xticks([0, 1])
    ax_gt.set_xticklabels(['Blocked\n(pairs we expected\nnot to cross)',
                            'Open\n(pairs we expected\nto cross)'], fontsize=12)
    
    # Legend
    legend_handles = [
        Patch(facecolor='#4169E1', alpha=0.7, label='Human framing '),
        Patch(facecolor='#FF8C00', alpha=0.7, label='Robot framing'),
        Line2D([0], [0], color="#9E1414", lw=3.5,
               linestyle=(0, (6, 3)), label='Researcher expectation'),
        Line2D([0], [0], color='#4169E1', lw=3.5,
       linestyle='solid', label='Group mean (Human)'),
        Line2D([0], [0], color='#FF8C00', lw=3.5,
       linestyle='solid', label='Group mean (Robot)'),
    ]

    ax_gt.legend(handles=legend_handles, fontsize=10, loc='lower right',
              frameon=True, framealpha=0.9)

    ax_gt.set_title('Survey Crossability Ratings vs Researcher Label\n'
                 '(24 complete respondents — between-subjects design)',
                 fontsize=13, fontweight='bold', pad=12)

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"---> GT comparison plot saved to: {output_path}")
    
#=======
# Creating statical analysis plots
# =========

def generate_statistical_analysis(output_path):
    # Load complete survey only
    df_raw = pd.read_csv(SURVEY_CSV)
    df_raw.columns = df_raw.columns.str.strip()
    max_page = df_raw['lastpage. Last page'].max()
    df_raw = df_raw[df_raw['lastpage. Last page'] == max_page].copy()

    likert = {'Strongly Disagree':0.0,'Disagree':0.25,'Neutral':0.5,
              'Agree':0.75,'Strongly Agree':1.0}
    records = []
    for col in df_raw.columns:
        m = re.match(r'^(R?)([A-Za-z0-9]+)\[SQ\d+\]\.\s+\[\[(\d+)[,\s]+(\d+)\]', col)
        if not m: continue
        scene, pair = m.group(2), f"[{m.group(3)},{m.group(4)}]"
        src = 'Robot' if m.group(1)=='R' else 'Human'
        for resp_idx, val in df_raw[col].dropna().items():
            if val in likert:
                records.append({'Respondent':resp_idx,'Scene':scene,
                                'Pair':pair,'Framing':src,'Score':likert[val]})
    survey = pd.DataFrame(records)
    survey['Scene_Pair'] = survey['Scene'] + '_' + survey['Pair']

    # ── Mixed ANOVA ───────────────────────────────────────────────────────────
    aov = pg.mixed_anova(data=survey, dv='Score', within='Scene_Pair',
                         between='Framing', subject='Respondent')
    aov_framing = aov[aov['Source']=='Framing'].iloc[0]
    aov_within  = aov[aov['Source']=='Scene_Pair'].iloc[0]
    aov_inter   = aov[aov['Source']=='Interaction'].iloc[0]

    print(f"Mixed ANOVA — Framing:     F={aov_framing['F']:.3f}, p={aov_framing['p_unc']:.4f}, η²={aov_framing['np2']:.3f}")
    print(f"Mixed ANOVA — Scene_Pair:  F={aov_within['F']:.3f}, p={aov_within['p_unc']:.2e}, η²={aov_within['np2']:.3f}")
    print(f"Mixed ANOVA — Interaction: F={aov_inter['F']:.3f}, p={aov_inter['p_unc']:.4f}")

    # ── T-test on spread per pair ─────────────────────────────────────────────
    std_per_pair = survey.groupby(['Scene','Pair','Framing'])['Score'].std().reset_index()
    std_per_pair.columns = ['Scene','Pair','Framing','Std']
    human_std = std_per_pair[std_per_pair['Framing']=='Human'].set_index(['Scene','Pair'])['Std']
    robot_std = std_per_pair[std_per_pair['Framing']=='Robot'].set_index(['Scene','Pair'])['Std']
    common = human_std.index.intersection(robot_std.index)
    h_std = human_std.loc[common].values
    r_std = robot_std.loc[common].values
    t_stat, p_ttest = stats.ttest_rel(h_std, r_std)
    #w_stat, p_wilcox = stats.wilcoxon(h_std, r_std)

    print(f"T-test: Human std μ={h_std.mean():.3f}, Robot std μ={r_std.mean():.3f}, t={t_stat:.3f}, p={p_ttest:.4f}")
    #print(f"Wilcoxon: W={w_stat:.0f}, p={p_wilcox:.4f}")

    # ── FIGURE ────────────────────────────────────────────────────────────────
    palette = {'Human':'#4169E1','Robot':'#FF8C00'}

    def fmt_p(p):
        if p < 0.001: return 'p < 0.001 (***)'
        elif p < 0.01: return f'p = {p:.3f} (**)'
        elif p < 0.05: return f'p = {p:.3f} (*)'
        else: return f'p = {p:.3f} (n.s.)'

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.patch.set_facecolor('white')

    # ── Panel A — Interaction plot ────────────────────────────────────────────
    ax = axes[0]
    means = survey.groupby(['Framing','Scene'])['Score'].mean().reset_index()
    scene_order = sorted(means['Scene'].unique())

    for framing, color in palette.items():
        grp = means[means['Framing']==framing].set_index('Scene').reindex(scene_order)
        mu = survey[survey['Framing']==framing]['Score'].mean()
        ax.scatter(range(len(scene_order)), grp['Score'],
                   color=color, s=80, zorder=3,
                   alpha=0.9, label=f'{framing} (μ={mu:.3f})')

    for i, scene in enumerate(scene_order):
        h = means[(means['Framing']=='Human') & (means['Scene']==scene)]['Score'].values
        r = means[(means['Framing']=='Robot') & (means['Scene']==scene)]['Score'].values
        if len(h) and len(r):
            ax.plot([i,i],[r[0],h[0]], color='gray', linewidth=1,
                    alpha=0.4, linestyle='-', zorder=1)

    ax.set_facecolor('#F8F8F8')
    ax.yaxis.grid(True, linestyle='--', alpha=0.4, linewidth=0.6)
    ax.set_axisbelow(True)
    ax.set_xticks(range(len(scene_order)))
    ax.set_xticklabels([re.sub(r'\d+','',s)+'\n'+s[-4:] for s in scene_order],
                       rotation=30, ha='right', fontsize=8.5)
    ax.set_ylabel('Mean Crossability Score', fontsize=12)
    ax.set_ylim(0, 1.1)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    ax.legend(fontsize=11, loc='upper right')
    ax.set_title('A — Mixed ANOVA\nMean Crossability per Scene by Framing',
                 fontsize=12, fontweight='bold')

    textstr = (
        f"Framing (between):  F={aov_framing['F']:.2f}, {fmt_p(aov_framing['p_unc'])}, η²={aov_framing['np2']:.3f}\n"
        f"Scene (within):     F={aov_within['F']:.2f}, {fmt_p(aov_within['p_unc'])}, η²={aov_within['np2']:.3f}\n"
        f"Interaction:        F={aov_inter['F']:.2f}, {fmt_p(aov_inter['p_unc'])}, η²={aov_inter['np2']:.3f}"
    )
    ax.text(0.01, 0.02, textstr, transform=ax.transAxes, fontsize=9,
            verticalalignment='bottom', fontfamily='monospace',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.9))

    # ── Panel B — T-test on spread ────────────────────────────────────────────
    ax2 = axes[1]
    std_long = pd.DataFrame({'Human':h_std,'Robot':r_std}).melt(
        var_name='Framing', value_name='Std')

    sns.violinplot(data=std_long, x='Framing', y='Std',
                   hue='Framing', palette=palette, inner=None, cut=0,
                   linewidth=1.5, ax=ax2, order=['Human','Robot'],
                   alpha=0.45, legend=False)
    sns.swarmplot(data=std_long, x='Framing', y='Std',
                  hue='Framing', palette=palette, order=['Human','Robot'],
                  size=4.5, alpha=0.85, edgecolor='black', linewidth=0.3,
                  ax=ax2, legend=False, warn_thresh=1.0)

    for i, (framing, color) in enumerate(palette.items()):
        m = h_std.mean() if framing=='Human' else r_std.mean()
        ax2.hlines(m, i-0.3, i+0.3, colors=color, linewidth=3.5,
                   linestyles='solid', zorder=6)
        ax2.text(i+0.33, m, f'μ={m:.3f}', va='center', fontsize=11,
                 color=color, fontweight='bold')

    y_top = max(h_std.max(), r_std.max()) + 0.03
    ax2.plot([0,0,1,1],[y_top,y_top+0.02,y_top+0.02,y_top],
             color='black', lw=1.2)
    sig = '***' if p_ttest<0.001 else ('**' if p_ttest<0.01 else ('*' if p_ttest<0.05 else 'n.s.'))
    ax2.text(0.5, y_top+0.02,
             f'Paired t-test: t={t_stat:.2f}, p={p_ttest:.4f} ({sig})',
             ha='center', fontsize=11, fontweight='bold')
    # ax2.text(0.5, y_top+0.00,
    #          f'Wilcoxon: W={w_stat:.0f}, p={p_wilcox:.4f}',
    #          ha='center', fontsize=9, color='gray')

    ax2.set_facecolor('#F8F8F8')
    ax2.yaxis.grid(True, linestyle='--', alpha=0.4, linewidth=0.6)
    ax2.set_axisbelow(True)
    ax2.set_ylabel('Standard Deviation of Crossability Ratings\n(per scene/pair)', fontsize=12)
    ax2.set_xlabel('Framing Condition', fontsize=12)
    ax2.set_title('B — T-test on Rating Spread\nConsensus: Human vs Robot Framing per Pair',
                  fontsize=12, fontweight='bold')
    ax2.text(0.5, -0.06, f'N = {len(h_std)} scene/pair combinations  |  α = 0.05',
             ha='center', transform=ax2.transAxes,
             fontsize=9, color='gray', style='italic')

    fig.suptitle('Statistical Analysis — Mixed ANOVA & Consensus Comparison\n'
                 '(24 complete respondents, between-subjects design, α = 0.05)',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"---> Statistical analysis saved to: {output_path}")

# ==========================================
# 3. PLOTTING PIPELINE
# ==========================================
def generate_composed_plot():
    print("Loading Survey Baseline Data...")
    #df_list = [load_and_format_survey_data(SURVEY_CSV)]
    
    survey_df, n_human_p, n_robot_p = load_and_format_survey_data(SURVEY_CSV)
    df_list = [survey_df]

    print("Loading VLM Prompt Data...")
    for prompt_label, csv_path in VLM_CSVS.items():
        if os.path.exists(csv_path):
            print(f" -> Found data for {prompt_label}")
            df_list.append(load_and_format_vlm_data(csv_path, prompt_label))
        else:
            print(f" -> WARNING: Could not find {csv_path}. Skipping.")
            
    df_master = pd.concat(df_list, ignore_index=True)
    
    unique_scenes = sorted(df_master['Base_Scene'].unique())
    num_scenes = len(unique_scenes)
    
    # 1. Dynamic Grid Calculation
    cols = 4
    rows = math.ceil(num_scenes / cols)
    
    # INCREASED FIGSIZE to handle 10 bars per pair
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 8, rows * 6))
    if num_scenes == 1: axes = [axes] # Handle single plot edge case
    else: axes = axes.flatten()
    
    # 2. Define the Expanded Color Palette
    # Strategy: Human/Robot are distinct. Prompts use Light (Raw) / Dark (Annotated) pairs.
    palette_colors = {
            'Human':              '#1f77b4',   # Strong Blue
            'Robot':              '#ff7f0e',   # Strong Orange

            'Prompt A Raw':       '#e31a1c',   # Strong Red
            'Prompt A Annotated': '#fb9a99',   # Light Red (clearly same family)

            'Prompt B Raw':       '#33a02c',   # Strong Green
            'Prompt B Annotated': '#b2df8a',   # Light Green

            'Prompt C Raw':       '#6a3d9a',   # Strong Purple
            'Prompt C Annotated': '#cab2d6',   # Light Purple

            'Prompt D Raw':       '#b8860b',   # Strong Gold/Dark Yellow
            'Prompt D Annotated': '#ffd700',   # Bright Yellow
                }
    
    # Filter the order to only include data we actually successfully loaded
    loaded_evaluators = df_master['Evaluator'].unique()
    evaluator_order = [e for e in palette_colors.keys() if e in loaded_evaluators]
    
    # 3. Plotting Loop
    for i, scene in enumerate(unique_scenes):
        ax = axes[i]
        df_scene = df_master[df_master['Base_Scene'] == scene].copy()
        
        # Sort numeric pairs correctly
        df_scene['Pair_Sort'] = df_scene['Pair'].apply(lambda x: [int(num) for num in re.findall(r'\d+', x)])
        df_scene = df_scene.sort_values(by='Pair_Sort')
        


        # Plot Boxes
        sns.boxplot(
            data=df_scene, x='Pair', y='Score', 
            hue='Evaluator', hue_order=evaluator_order, 
            palette=palette_colors, showfliers=False, 
            boxprops=dict(alpha=0.3),  
            zorder=1, linewidth=1.2, ax=ax
        )
        
        # 2. THE STRIPPLOT (The Foreground Layer)
        # dodge=True ensures the dots align perfectly over their respective boxes.
        # zorder=2 forces the dots to physically draw on top of the boxes.
        # linewidth=0.3 and edgecolor='black' puts a tiny ring around each dot so they pop!
        sns.swarmplot(
            data=df_scene, x='Pair', y='Score',
            hue='Evaluator', hue_order=evaluator_order,
            palette=palette_colors, dodge=True,
            size=3.5, alpha=0.9, zorder=2,
            edgecolor='black', linewidth=0.3,
            ax=ax, legend=False,
            warn_thresh=1.0  # suppress overlap warnings
        )
        
        # Subplot specific formatting
        ax.set_title(f'Scene: {scene}', fontsize=16, fontweight='bold', pad=10)
        ax.set_facecolor('#F8F8F8')
        ax.yaxis.grid(True, linestyle='--', alpha=0.5, linewidth=0.6, color='gray')
        ax.set_axisbelow(True)
        ax.set_ylim(-0.05, 1.05)
        ax.set_xlabel('Interacting Pair (IDs)' if i >= num_scenes - cols else '', fontsize=12)
        ax.set_ylabel('Crossability Probability' if i % cols == 0 else '', fontsize=12)
        
        # Remove individual legends
        if ax.get_legend() is not None:
            ax.get_legend().remove()

        fig_single, ax_single = plt.subplots(figsize=(12, 5))
        def_scene_sorted = df_scene.sort_values(by='Pair_Sort')
        sns.boxplot( data=def_scene_sorted, x='Pair', y='Score', 
            hue='Evaluator', hue_order=evaluator_order, 
            palette=palette_colors, showfliers=False, 
            boxprops=dict(alpha=0.3),  
            zorder=1, linewidth=1.2, ax=ax_single, legend=False )
        sns.stripplot( data=def_scene_sorted, x='Pair', y='Score',
            hue='Evaluator', hue_order=evaluator_order,
            palette=palette_colors, dodge=True, jitter=0.2,
            size=3.5, alpha=0.9, zorder=2,
            edgecolor='black', linewidth=0.3,
            ax=ax_single, legend=False )
        
        ax_single.set_facecolor('#F8F8F8')
        ax_single.yaxis.grid(True, linestyle='--', alpha=0.5, linewidth=0.6)
        ax_single.set_axisbelow(True)
        ax_single.set_ylim(-0.05, 1.05)
        ax_single.set_title(f'Scene: {scene}', fontsize=16, fontweight='bold')
        ax_single.set_xlabel('Interacting Pair (IDs)', fontsize=12)
        ax_single.set_ylabel('Crossability Probability', fontsize=12)
        handles = [plt.scatter([], [], color=palette_colors[eval], s=40, label=eval) for eval in evaluator_order]
        fig_single.legend(handles=handles, labels=evaluator_order, title='Evaluation Source', loc='upper center', bbox_to_anchor=(1.05, 1), borderaxespad=0, fontsize=9, title_fontsize=10, frameon=True)
        fig_single.tight_layout()
        fig_single.savefig(os.path.join(OUTPUT_INDIVIDUAL_PLOT_DIR, f'{scene}_crossability_analysis.png'), dpi=300, bbox_inches='tight')
        plt.close(fig_single)
    print(f"---> Individual scene plots saved to: {OUTPUT_INDIVIDUAL_PLOT_DIR}")
    
    # Clean up empty subplots
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    # 4. Global Legend (Forced into 5 columns so it stacks neatly in 2 rows at the top)
    handles, labels = axes[0].get_legend_handles_labels()
    
    # Filter handles to match the evaluator order
    legend_dict = dict(zip(labels, handles))
    ordered_handles = [legend_dict[lbl] for lbl in evaluator_order if lbl in legend_dict]
    
    fig.legend(ordered_handles, evaluator_order, title='Evaluation Source', loc='lower center', 
           bbox_to_anchor=(0.5, 0.0), ncol=5, fontsize=12, title_fontsize=14)
    plt.tight_layout(rect=[0, 0.08, 1, 1])  # Leave space at the top for the legend

    plt.savefig(OUTPUT_PLOT_FILE, dpi=300, bbox_inches='tight')

    plt.close()

    generate_violin_plot(df_master, OUTPUT_VIOLIN_FILE, n_human_p, n_robot_p)

    generate_gt_comparison_plot(df_master, GT_CSV, OUT_GT_FILE)
    generate_statistical_analysis(OUTPUT_STATS_FILE)

    print(f"---> Master composed plot saved to: {OUTPUT_PLOT_FILE}")

if __name__ == "__main__":
    generate_composed_plot()
